### ISSUE TITLE
Suppress setup failure error

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/internet-draft-template#2]
The setup action does a bunch of things, relying on an early fail to avoid running later steps when things aren't correct.  This is mostly fine, except that people will get a "Failed Action" email when they create the repo.  Though the output of the action explains this, it's messy. 

It is possible to have the action succeed and complete, but it does mean running the entire setup process as a single "run" step in the action.  That would then not fail; it would succeed but do nothing if things weren't ready yet.

This would require a rewrite of the action so that it didn't use the action to perform the main setup step.  That would mean pulling the docker image manually and running the setup steps directly.

That's a fairly major change to the way this works, but it might be worthwhile doing anyway (especially as it means that the special setup steps wouldn't need to be part of the entrypoint script).

**Comment by Cibai000** [comment]
Failed action

**Comment by Cibai000** [comment]
@DavidSchinazi  failed action
