### ISSUE TITLE
working drafts not parsed in references

### ISSUE THREAD

**Issue by hmntsharma** [martinthomson/internet-draft-template#30]
Hi,

Currently, the normative and/or informative references do not parse drafts but only RFC.
If they are added, then the github actions fail.

Please look into this.

Thanks!
Hemant

**Comment by martinthomson** [comment]
I'm afraid that I don't understand what you are getting at.  Can you say more?

**Comment by hmntsharma** [comment]
The following build failed when I referenced one of my drafts

❌ draft-hmntsharma-bmp-over-tls

❌ step 'xml2rfc-html' failed
draft-hmntsharma-bmp-over-tls.xml(0): Error: IDREF attribute target references an unknown ID "draft-hmntsharma-bmp-tcp-ao", at None
/github/workspace/draft-hmntsharma-bmp-over-tls.xml(10): Error: Invalid document before running preptool.
Unable to complete processing draft-hmntsharma-bmp-over-tls.xml

❌ step 'xml2rfc-txt' failed

draft-hmntsharma-bmp-over-tls.xml(0): Error: IDREF attribute target references an unknown ID "draft-hmntsharma-bmp-tcp-ao", at None
/github/workspace/draft-hmntsharma-bmp-over-tls.xml(10): Error: Invalid document before running preptool.
Unable to complete processing draft-hmntsharma-bmp-over-tls.xml

Please help.

**Comment by hmntsharma** [comment]
Run martinthomson/i-d-template@v1
/usr/bin/docker run --name ghcriomartinthomsonidtemplateactionlatest_c0aaad --label 160[5](https://github.com/hmntsharma/draft-hmntsharma-bmp-over-tls/actions/runs/9736374655/job/26866910139#step:6:6)7a --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_MAKE" -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/draft-hmntsharma-bmp-over-tls/draft-hmntsharma-bmp-over-tls":"/github/workspace" ghcr.io/martinthomson/i-d-template-action:latest  "all"
git clone -q --depth 10  \
    -b main https://github.com/martinthomson/i-d-template lib
warning: lib/default-branch.py: correcting the default branch locally:
warning: lib/default-branch.py:     git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
VERSIONED="versioned" lib/build-targets.sh draft-hmntsharma-bmp-over-tls >>.targets.mk
make: '.targets.mk' is up to date.
cat draft-hmntsharma-bmp-over-tls.md  | kramdown-rfc --v3 | lib/trace.sh draft-hmntsharma-bmp-over-tls.xml -s venue python3 lib/add-note.py | lib/trace.sh draft-hmntsharma-bmp-over-tls.xml -s v2v3 xml2rfc -q --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/github/workspace/.refcache --v2v3 /dev/stdin -o /dev/stdout >draft-hmntsharma-bmp-over-tls.xml
*** don't know how to expand ref draft-hmntsharma-bmp-tcp-ao
/github/workspace/.refcache/reference.RFC.4303.xml: fetching from https://bib.ietf.org/public/rfc/bibxml/reference.RFC.4303.xml
/github/workspace/.refcache/reference.RFC.43[6](https://github.com/hmntsharma/draft-hmntsharma-bmp-over-tls/actions/runs/9736374655/job/26866910139#step:6:7)4.xml: fetching from https://bib.ietf.org/public/rfc/bibxml/reference.RFC.4364.xml
lib/trace.sh draft-hmntsharma-bmp-over-tls.txt -s xml2rfc-txt xml2rfc -q --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/github/workspace/.refcache --text --no-pagination draft-hmntsharma-bmp-over-tls.xml -o draft-hmntsharma-bmp-over-tls.txt
draft-hmntsharma-bmp-over-tls.xml(0): Error: IDREF attribute target references an unknown ID "draft-hmntsharma-bmp-tcp-ao", at None
/github/workspace/draft-hmntsharma-bmp-over-tls.xml([10](https://github.com/hmntsharma/draft-hmntsharma-bmp-over-tls/actions/runs/9736374655/job/26866910139#step:6:11)): Error: Invalid document before running preptool.
Unable to complete processing draft-hmntsharma-bmp-over-tls.xml
make[1]: *** [lib/main.mk:[11](https://github.com/hmntsharma/draft-hmntsharma-bmp-over-tls/actions/runs/9736374655/job/26866910139#step:6:12)6: draft-hmntsharma-bmp-over-tls.txt] Error 1
lib/trace.sh draft-hmntsharma-bmp-over-tls.html -s xml2rfc-html xml2rfc -q --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/github/workspace/.refcache --html --css=lib/v3.css --metadata-js-url=/dev/null draft-hmntsharma-bmp-over-tls.xml -o draft-hmntsharma-bmp-over-tls.html
draft-hmntsharma-bmp-over-tls.xml(0): Error: IDREF attribute target references an unknown ID "draft-hmntsharma-bmp-tcp-ao", at None
/github/workspace/draft-hmntsharma-bmp-over-tls.xml(10): Error: Invalid document before running preptool.
Unable to complete processing draft-hmntsharma-bmp-over-tls.xml
make[1]: *** [lib/main.mk:111: draft-hmntsharma-bmp-over-tls.html] Error 1
make[1]: Target 'latest' not remade because of errors.
rm draft-hmntsharma-bmp-over-tls.xml
make: *** [lib/main.mk:[16](https://github.com/hmntsharma/draft-hmntsharma-bmp-over-tls/actions/runs/9736374655/job/26866910139#step:6:17): all] Error 2

**Comment by hmntsharma** [comment]
> I'm afraid that I don't understand what you are getting at. Can you say more?

I have updated some more information. 
Thanks for checking this out!

**Comment by martinthomson** [comment]
The correct way to create a citation to an internet draft is `{{?TCP-AO=I-D.hmntsharma-bmp-tcp-ao}}` (where "?TCP-AO" can also be "!TCP-AO" and "TCP-AO" could be any label you prefer).  However, that means that the draft needs to be submitted to the IETF datatracker.

("ID" in this case refers to the identifier of the XML element, not "Internet-Draft".)

For drafts that aren't, you will need to create a reference yourself.
