### ISSUE TITLE
Detect version change of Python

### ISSUE THREAD

**Issue by bwesterb** [martinthomson/internet-draft-template#33]
Run into trouble after `python3` pointed to a newer version of Python (`3.13`). Solution was to run `make clean-venv` first. Might be nice to detect change of Python version automatically.

**Comment by bwesterb** [comment]
Scratch that. Still seems broken in 3.13 because of `lxml`.

**Comment by martinthomson** [comment]
FWIW, you aren't the only one who has hit this problem.  Yes, the problem is related to lxml installation and I have no ability to debug it.  If you work out what to do (other than the pin the python version), let me know.
