### ISSUE TITLE
Kramdown reference would be useful in README.md

### ISSUE THREAD

**Issue by dgpetrie** [martinthomson/internet-draft-template#5]
It would be useful to have a link/reference to https://github.com/cabo/kramdown-rfc in the README.md.  It took a little hunting for me to realize kramdown was being used to build the draft.

**Comment by martinthomson** [comment]
There is a reference here:
https://github.com/martinthomson/internet-draft-template/blob/aea8c38862898a132991fa958eafda196868e92c/draft-todo-yourname-protocol.md?plain=1#L17

That seems like it is a more timely location.

The README is the first thing you see after creating a new repository; keeping that short and to the point is critical to the usability of the overall process.  I don't want to put too much detail there.
